---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    # A Task can have multiple steps
    - name: echo
      image: registry.access.redhat.com/ubi9/ubi:latest
      script: |
        #!/bin/sh
        echo "Hello World"

    - name: echo-again
      image: registry.access.redhat.com/ubi9/ubi:latest
      script: |
        #!/bin/sh
        echo "Hello Again"
